# Generated by Django 3.2.8 on 2021-11-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='items_Json',
            new_name='item_Json',
        ),
    ]
